2024-01-02 16:45:10,364 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-02 16:45:10,364 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Configure stats pid to 1484
2024-01-02 16:45:10,364 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Loading settings from /content/openset_domain_adaptation/wandb/settings
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:_log_setup():524] Logging user logs to /content/openset_domain_adaptation/wandb/run-20240102_164510-q0fc18ha/logs/debug.log
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:_log_setup():525] Logging internal logs to /content/openset_domain_adaptation/wandb/run-20240102_164510-q0fc18ha/logs/debug-internal.log
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x783cb2981bd0>
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:init():564] calling init triggers
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:init():614] starting backend
2024-01-02 16:45:10,365 INFO    MainThread:1484 [wandb_init.py:init():618] setting up manager
2024-01-02 16:45:10,371 INFO    MainThread:1484 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-02 16:45:10,371 INFO    MainThread:1484 [wandb_init.py:init():624] backend started and connected
2024-01-02 16:45:10,392 INFO    MainThread:1484 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-02 16:45:14,457 INFO    MainThread:1484 [wandb_init.py:init():716] updated telemetry
2024-01-02 16:45:14,462 INFO    MainThread:1484 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-02 16:45:14,899 INFO    MainThread:1484 [wandb_run.py:_on_init():2254] communicating current version
2024-01-02 16:45:15,049 INFO    MainThread:1484 [wandb_run.py:_on_init():2263] got version response 
2024-01-02 16:45:15,049 INFO    MainThread:1484 [wandb_init.py:init():800] starting run threads in backend
2024-01-02 16:45:15,090 INFO    MainThread:1484 [wandb_run.py:_console_start():2233] atexit reg
2024-01-02 16:45:15,090 INFO    MainThread:1484 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-02 16:45:15,090 INFO    MainThread:1484 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-02 16:45:15,090 INFO    MainThread:1484 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-02 16:45:15,091 INFO    MainThread:1484 [wandb_init.py:init():841] run started, returning control to user process
2024-01-02 16:45:15,092 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set num_epochs = 15 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,093 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb num_epochs 15 None
2024-01-02 16:45:15,093 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set device = cuda - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,093 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb device cuda None
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set batch_size = 8 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb batch_size 8 None
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set dataset_choice = Giacomo - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb dataset_choice Giacomo None
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set subset_flag = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb subset_flag False None
2024-01-02 16:45:15,094 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set obs_num = 30 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb obs_num 30 None
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set num_classes_to_remove = 2 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb num_classes_to_remove 2 None
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set g_open_set = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb g_open_set False None
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set hard_reset = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,095 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb hard_reset False None
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set class_validation = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb class_validation False None
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set adaptation_direction = hmdb2ucf - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb adaptation_direction hmdb2ucf None
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set baseline_or_proposed = proposed - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb baseline_or_proposed proposed None
2024-01-02 16:45:15,096 INFO    MainThread:1484 [wandb_config.py:__setitem__():151] config set criterion_label_classifier = CrossEntropyLoss() - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x783cb2982f50>>
2024-01-02 16:45:15,097 INFO    MainThread:1484 [wandb_run.py:_config_callback():1342] config_cb criterion_label_classifier CrossEntropyLoss() None
2024-01-02 16:45:15,427 INFO    MainThread:1484 [wandb_watch.py:watch():51] Watching
2024-01-02 16:45:57,653 INFO    MainThread:1484 [wandb_run.py:_finish():1962] finishing run sango/openset_domain_adaptation/q0fc18ha
2024-01-02 16:45:57,653 INFO    MainThread:1484 [jupyter.py:save_history():445] not saving jupyter history
2024-01-02 16:45:57,654 INFO    MainThread:1484 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-02 16:45:57,654 INFO    MainThread:1484 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-01-02 16:45:57,654 INFO    MainThread:1484 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 1
2024-01-02 16:45:57,654 INFO    MainThread:1484 [wandb_run.py:_restore():2185] restore
2024-01-02 16:45:57,654 INFO    MainThread:1484 [wandb_run.py:_restore():2191] restore done
2024-01-02 16:46:04,362 INFO    MainThread:1484 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-02 16:46:04,363 INFO    MainThread:1484 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-02 16:46:04,368 INFO    MainThread:1484 [wandb_run.py:_footer_sync_info():3796] logging synced files
